language: python

python:
  - "2.7"

install: true

script: true

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: launchpad
  slug: "~arsenyme/slack-notifier/master"
  oauth_token:
    secure: iD2LdMZuzMrSuPJT8Yv9J1XzfCr/jjPeoJCYkpyXakIXrBzza33nm9gU+otXJNy1Z5Gmo0hRldNmpbd2edK4g+WFyye4/+/gkiHaULBEGyvfGEOXBr0ps0Co+/hFrw5tYUficEN2VCuZvhnTxLXKEbNrO7oTqzdrlM/uaTwF/2T5VhkVykaXdq6PwkgpBzJsQKDf6fbvfMYDt9G17uJaE6bLxibvvDqhXM3SUOETSxx9MCtsLEBX93hwJ3RBBkrngc9btNqnTJxD9zpogfl/pi7HT/8MNraEQ/+6RW7irGlcJgSlqQfv6fkCtxpvttJN07MgFxuzchrIKoPiFhS03rUrG6t7sduIwZa+jMgwMrG9hW0aIuz4ykUB1wp5YWwuF3fDM9V7pdoeD/+1nNvaBjBgmQqkKzRH0t1q0WHnObTO0C57omBXiPuHBD3ONHyVoYURfr/7cvharmdebOxtDDmX7U8IrY5+g820le+4utLkXF64MIBso1u5gjhH7kPswx/j18WX7Y9U+55UvS+NdlddeSMeWVDf6fgmeiO2lzuwIc2eL4+WIEQFkAs+iJb6kNFyEsV2FrMgYAC/lfzBGtGQ+RxVwuZXi3p1ewU6nBEu2AFO4ofIJsjIvrpfKj7ZBROZUByJMTDH3D0GcnQoBcfPPd2vC8QysiMrKakT4/E=
  oauth_token_secret:
    secure: AEm/tqkQAXRIsG7NR1/8r84iAoz/Ounin1I9nAs+sqBNTGDVwzzbDyCchXBnyZDg61TzpIyKz9zZt9J1IdWDYVEwdm1FiVDWQ08xjE1tgA9Z2roP/dHh1LZkaR4maGTrgQmfrhNk70S/Ii+uqickp3uc9FRsjXJnViXJmHRSQHSITQQTkcg02uynIpehS1APskRfL+B0dGfSLvuykdUz18K4kkbVEpBGL2bh0pllKxxZOtkpHdPF9Je5UQnudUO82hafuxs0/UCGAMZ3mTagiMTmRaSDacJFXAfHDnE9BWpqUMlPfE/4mMfAZ5pFsTSYJhMGvx25hzGPdMZyhxJJcfLOFQzAyotoIeatcqRR9eSaa5ap3RoeIwekZyMpauovIxZNPMsSV2s8XGAv8udgk4+qGWAOfnlO55ImnoyAneNd4wJ/dCRqu/04groEs3GVKIqbNRUZqmCnF37odiUvrKEv4DQ2ENOAqJ6x8+vm7pruWJ3yLs9Hdh/luROMP5pJMfx0qhcvqn/07s1114snOl0o/2B3XyYeqSa6pf7vXO2LOzRu+sA4P2w4HoilKFmITqRHXWszymMI0Xf36zdvxVwmDt11Il727iANcTqxN8BbsC3+vvCJJ/nNzCEXtQQ8XeLYi/TZ62iP9EH907XNdOebsxD9peB0EaJL0ONftCQ=
