language: python

python:
  - "2.7"

install: true

script: true

deploy:
  skip_cleanup: true
  on:
    branch: master
  provider: launchpad
  slug: "~arsenyme/slack-notifier/master"
  oauth_token:
    secure: OqOIpAaEHzyCtJnunhqjbMv1o2GDOf5QAVR6tDX9JQvFCCH9rmlNn/YVczWZj/PopJhzj+AYugMX2DeV6EIB+YN5vX8YeXTzuGfeXja9t/TwQqP4cPpCxry4AfQ+Rv1yo3e84lKdT6WF5ATaOgpYjYLrdGK8eXKVvcw2wYJwYQTPztrcm6sv6mGBq03DP2QuopgRJNNAJtjuneeC0Co1Shoa9r9O0jJfIejn8Ht3iAYXFLEd5JTk6QjoGVr/PpT7dvMLTyfaq+X3Gp8o0j2LveXRAwqMVLy9NSPPyybzvhft/OJeXWt7164p9qUkVcHJHreHyruQr5Dm8iEwYnKUjYUEMmY3JMguE+dV8Zox3wdU3Lmso3okhiZM6DqEkd+8cQi0HfDV+F0Wi6pIzQty4w533WiM34Ah+KOQc1Nz4khX9NDfypsoB/rKd5HTLSZQ5bT2fkeCXHesvFkl1jVCUbHNPXo9Y/qmXk8U0ry606ML1GbNrhPEpHSM6g4xAWRw3wnfrrfWtyqo+ty5Nei6SuwpFwTGfy55IzDzqqxzOcHtc+w4XFUZak2pe6ptwsM0CL+Q7tzItYAnmBUMD87Do85nYt7hLl4XLqizg37+lX26fozzJXKUDUZgZRyBHJslm6lyQk9NpIfsSO4BZ1SQdB66ELZuz7EwpZCsRFOYhnM=
  oauth_token_secret:
    secure: RTH9TPnJAhLHua09YEFQgRpd8xq5Vskzl9TzjmKfs0Ohap8UhVS6t6uXgaqftAsruJvTc+OxZSCyEq/LlR93TR4W05cdzVdkAKhdLgdf2f0uOiJ3ljliqFd+5MAHJAlyy1KOUcaGdQs+NZFk+uALjKtlALNhJhI7gP1CYDoC14Weod4FAFBJELhTG1bJ5DnXE+4Ju3HzItRX6S6yO5LxyT3Qk2tKChZW+bTeWLwz6BbeAA/F0MaqVI5q/lykPN4w//X6JKAcXIE/NYtrtNaNxt1FYCKy68VsO6Hn6EBs0vOFgBjiwO0QB1qK/qTa3Wf1295H1LYyeE9zctPwrK74iDb6MKzwagtGpWdgxR1uNTEmrhuEi9xVZT51wZWuSdjTdotw7nEe6qAcYSYE+lRrOaaHT3I4CvfP5stO60xLSixdCtDVu3TJ3lXr974psYUFtjvTxO5CTzUMbiwHen3KdXQavCP+DPpzERZKPGYdajnJWtQ2Ib7GfgZk/JMCqvOaWOnLmppxmEc2ztmEdzmK+DApQ/nhU80NrQ7c6nYMRHNLttImvXK9xixWTis0NGMf7yVoWJdgea4gbawQGgf7xCn24cBPeXdwEWBZm/bUiLRECbIcxrQAUrUFIjOFHJCKU8xFqqb4gvJq8pzLxU1y14uwldGrdiL6dMVainC72gg=
